safe: false
auto: true
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000

source: .
destination: ./_site
plugins: []

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
